### ISSUE TITLE
Permanently disable links

### ISSUE THREAD

**Issue by Coupe70** [fabiosangregorio/links-disabler#3]
Would it be possible to have an option to always disable links or to have 
'Disable Links' activated instead of deactivated for every opened website 
by default? 
I would like to allow elderly people to scroll through certain websites on a tablet
without following any links by mistake.

**Comment by fabiosangregorio** [comment]
Hi @Coupe70, thank you for trying out the extension.
This is a great enhancement: I thought about having a global setting which toggles the extension browser-wide instead of tab-wise.
I will study how to do this and then implement it. 
Thank you for the suggestion!

Regarding what you said about tablets: I am not aware about extension support for android/iOS tablets, are you talking about Windows tablets?

**Comment by fabiosangregorio** [comment]
Version 1.3.0 is available now on the Chrome Web Store and includes this functionality.
